### ISSUE TITLE
Support SRFI-115

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#501]
PR #495 is a start, but there's still work to do. I'll try to finish it. This is to keep track of the work, and also to serve as a Q&A channel especially when it comes to design changes.

 - [x] basic sre-to-ast transformation #495
 - [x] support start/end for searching in a subtring, #502 
 - [x] add srfi-115 api, work out incompatibilities with gauche.regexp (hopefully none)
 - [x] support bos and eos
 - [x] probably update regexp-replace(-all) to support both srfi-115 and gauche semantics #503
 - [x] support `'pre` and `'post` in `regexp-replace` #527 (already supported, but buggy)
 - [x] support bog, eog and grapheme, #618 #620
 - [x] consider gauche extension to sre since srfi-115 does not utilize full gauche regexp engine capabilities #531 
 - [x] documentation #505

**Comment by pclouds** [comment]
So first question, bos and eos support.

If I read the regexp engine correctly, guache currently only support matching one line. bol and eol then are essentially bos/eos. If so, we could juse rename AST symbol names from bol/eol to bos/eos ('^' and '$' will still produce bos/eos). Then we can reintroduce true bol/eol later, which the option to support multi line even with if gauche regexp api (I'm thinking another keyword like `:case-fold`).

One thing to clarify is bos/eos (i.e. the current bol/eol) behaviour inside capture groups. This is based purely on documentation, but bos/eos in a group will always match the beginning/end of that group. I don't see SRFI-115 mentioning SRE bos/eos behavior inside capture groups at all. I suppose we could accept this as gauche extension to SRE and move on?

The other option is to update regexp engine to always match bos/eos to the string, not the group. A bit more work, and I'm not sure if it's really worth srfi-115 compliance...

Thoughts?

**Comment by shirok** [comment]
First point - the premise of Gauche regexp engine is that you shouldn't try to match regexp against long strings---you'd better split the input strings coarsely then use regexp on each chunk, in most case each line.  That's why we didn't distinguish bos/eos and bol/eol.  However, to be compatible with SRE, I'm ok to make the current bol/eol to bos/eos.   Technically it can break backward compatibility with the code that deal with regexp AST, but I assume there's not much of such code now.

Second, about group and bos/eos.  Do you mean something like #/(^ab)|cd/ which matches "xycd"?
I believe this is consistent with other engine like PCRE but I need to double check.  My intention is to match with the current general practice.

**Comment by pclouds** [comment]
> Technically it can break backward compatibility with the code that deal with regexp AST

Right. I forgot AST is actually exposed in scheme. I'll switch bol/eol semantics based on some multi-line flag then

> Do you mean something like #/(^ab)|cd/ which matches "xycd"?

It's this part. I'm not sure I really get it

> For the sake of     recognizing those characters, lookahead/lookbehind assertions     (‘(?=...)’, ‘(?!...)’, ‘(?<=...)’, ‘(?<!...)’) and atomic      clustering (‘(?>...)’) are treated as if they are a whole pattern.      That is, ‘^’ at the beginning of those groupings are      beginning-of-string assertion no matter where these group appear in      the containing regexp.  So as ‘$’ at the end of these groupings.

**Comment by pclouds** [comment]
> Second, about group and bos/eos. Do you mean something like #/(^ab)|cd/ which matches "xycd"?
> I believe this is consistent with other engine like PCRE but I need to double check. My intention is to match with the current general practice.

The relevant commit is 12e53d50e3ca14dd3ea143657d249c00231df128 which mentions "consistent with Perl and Oniguruma". Maybe it's just about '^' ambiguity in the pattern string, not the `bol` ast node.

**Comment by pclouds** [comment]
Third point. How do you want to handle the name clashes of `regexp-replace` and `regexp-replace-all`? The SRFI one obviously also takes SRE. The 'substition' is also different. And the SRFI one takes more optional arguments...

**Comment by shirok** [comment]
The substitution part doesn't overlap with the current one, so it's ok.  The only clashing case is when rx is a string, in which case it can be a string-representation of regexp (Gauche) or a literal string (SRE).  It is unresolvable automatically, so we inevitably have gauche#regexp-replace and srfi-115#regrexp-replace, but we can make gauche#regexp-replace dispatch SRE when rx is not a simple string (the user can always make it dispatch to sre version passing (seq "string").)   srfi-115#regexp-replace is for the compatibility with third-party code.

Actually I don't like having two sets of match-and-replace code, so I'll make the built-in one generic, and let srfi-115 one just wrap rx with seq when it's a string.

**Comment by pclouds** [comment]
I'm adding SRE syntax for conditional patterns `(?(?=..))` but I have problem understanding cpat in the AST. cpat is described as

    (cpat <condition> <ast> <ast>)

but it does not look like that

```
gosh$ (regexp-ast #/(?(?=a)bc)/)
(0 #f (cpat (assert #\a) (#\b #\c) ()))
```

since the "then" pattern is wrapped in "()" but it is not preceded by `'seq` like normal sequences.  I would expect something like

    (0 #f (cpat (assert #\a) (seq #\b #\c) ()))

Weirder is when both "then" and "else" are specified

```
gosh$ (regexp-ast #/(?(?=a)bc|de)/)
(0 #f (cpat (assert #\a) ((seq #\b #\c)) ((seq #\d #\e))))
```

Here we see "bc" is a proper sequence, but it's still wrapped by an extra "()". The same for "de".

I could probably figure out from regexp.c but it'll take some time. If you already have some clue, that would be great.

**Comment by shirok** [comment]
Good catch.  Currently, the 'then' pattern and 'else' pattern are both treated as if in seq.  I'll adjust the document.

**Comment by pclouds** [comment]
Thanks. These are the proposed extended SRE syntax to cover other Gauche regexp features before I send the code. The syntax is added for two reasons

* to be able to do everything within SRE
* to be able to display everything with SRE, even if the given regexp was created by RE string

    (no-backtrack <sre>...)

This is the same as `(?>pattern)` or AST node `once`. Better name is welcome (maybe "fixed"?) I just don't find "once" very intuitive

    (if <cond-sre> <then-sre> [<else-sre>])
    (unless <cond-sre> <then-sre> [<else-sre>])

These are `(?(?=condition)...)` and `(?(?!condition)...)`. I'm not entirely happy with the name `unless` here because it deviates from rnrs `unless` form. But I don't know any better name, perhaps `if-not`? Recognizing `(if (not <sre>) ..)`  is also an option, but that may mislead people because `not` is not really generic SRE syntax.

**Comment by shirok** [comment]
I don't remember why I named `(?>pattern)`  `once`.  I've seen it called "atomic" pattern or "independent" subexpression in other engine, so those names may be other candidates.

As for conditionals, I think I avoided `if` so that AST won't be confused with code.  But SRE already use `or, so `if` is ok.  We already have `look-ahead`/`neg-look-ahead` in SRE so I don't see why you need `unless`/`if-not` --- `(?(?=RE)...)` becomes `(if (look-ahead RE) ...)` and `(?(?!RE)...)` becomes `(if (neg-look-ahead RE) ...)`, aren't they?

**Comment by pclouds** [comment]
> I don't remember why I named `(?>pattern)` `once`. I've seen it called "atomic" pattern or "independent" subexpression in other engine, so those names may be other candidates.

OK I'll go with "atomic". We can change it later when the PR is opened.

> As for conditionals, I think I avoided `if` so that AST won't be confused with code. But SRE already use `or, so `if`is ok.

The same reason may be applied to SRE, I guess.

> We already have`look-ahead`/`neg-look-ahead`in SRE so I don't see why you need`unless`/`if-not`---`(?(?=RE)...)`becomes`(if (look-ahead RE) ...)`and`(?(?!RE)...)`becomes`(if (neg-look-ahead RE) ...)`, aren't they?

Well yes, but SRE still can't do realy conditional patterns like Gauche RE. And the other reason is displaying SRE from any AST. Without new syntax we would not be able to handle `cpat` AST node.

**Comment by pclouds** [comment]
I think I'm slowly getting your last question. So

    (?(?=test)then|else)

could be converted to

    (or (seq (look-ahead test) then))
        else)

Yes? I think it works if

* "test" matches and "then" also matches, "else" will be ignored
* "test" does not match, "else" will be tried

But if "test" matches and "then" does not, the "or" expression would try the  "else" pattern and could match something, that's not expected by `(?(?=)...)` is it?

**Comment by pclouds** [comment]
Gauche's SRE fails one chibi test, to be investigated later...

    (test-re '("σζ\x01C5;") '(w/nocase (* lower)) "σζ\x01C5;")

**Comment by pclouds** [comment]
> Gauche's SRE fails one chibi test

It's #598

**Comment by pclouds** [comment]
Any idea how to handle the grapheme situation? SRE allows to match grapheme boundary, but grapheme cluster detection is in Scheme code while regex engine is in C. I see two options but neither is pretty:

* Call Scheme code from C regex engine
* Move grapheme code down to C

**Comment by pclouds** [comment]
OK after looking more at grapheme code in gauche.unicode, here's my plan:

- move the two cise functions wb-property and gb-property into the core, exported from gauche.internal, unicode_attr.h is likely included in either char.c or unicode_attr.c
  - this makes it possible to move gauche.unicode back to lib (or libsrc if you still want to precompile it)
- introduce a new finite state machine for grapheme boundary detection in regexp.c. The one in gauche.unicode is really tied to splitting strings.
   - this means we have _two_ finite state machines for grapheme, a Scheme one in gauche.unicode and a C one in regexp.c.
- adding support for grapheme in regexp.c, mostly new AST but probably no new regex syntax (pcre seems to have grapheme syntax we can borrow)
- bog, eog and grapheme can be finally supported in sre.scm

**Comment by shirok** [comment]
The issue is that (1) the C engine runs on octet stream rather than codepoint stream, but grapheme state machine needs to be based on codepoint stream, and (2) the grapheme cluster needs to run from the beginning of the input.  So I'd like to find the grapheme cluster boundary lazily.

My hunch is this:
- A grapheme boundary marker is a separate routine, which receives an octet string, start and end point, and "marks" the cluster boundary.
- BOG/EOG compiles into new regex instructions.
- When regex VM encounters BOG/EOG instruction, it checks if the current point of input is already marked with grapheme boundary marker.  If not, it calls the marker from the last known grapheme cluster boundary (or the beginning of input) to the current point, to mark up the boundaries, then check BOG/EOG assertion.

With this scheme, the grapheme boundary marker can be in Scheme---there's overhead, but I'd expect bog/eog is used rarely and we can put off optimizations until needed.

This does need O(n) extra memory to store grapheme boundaries, but you don't need to save the state of grapheme state machine for backtracking.  And it costs nothing if bog/eog is never tested.

**Comment by pclouds** [comment]
Hmm.. in the spirit of putting off optimization until necessary, how about we run grapheme thing _early_ but only when needed?

If SRE compiler detects grapheme, it runs the grapheme marker over the entire string, saves the result. Then it passes both AST and the grapheme results down to regex engine to use.

This way regex does not have to call back to Scheme. The only difficulty is maybe finding out codepoints from byte stream in C code... Overhead is even higher (for simpler code) but only when people actually use graphemes.

**Comment by shirok** [comment]
Even if SRE contains bog/eog, it is possible that the branch won't be visited, and the string is rejected early so the marking of entire string is likely to be wasted.  However, I agree that we can go with early-marking strategy first, then optimize it later.

Calling Scheme from C isn't a big deal at all, except it lacks documentation.  Search `SCM_BIND_PROC` in the source.  We can add a support procedure that returns a (uniform) vector of integer indexes, which is easier to access from C.

It is nice if the code is constructed so that it'll be easier to move to lazy marking later.   Changing public C API is a big deal, so we want to avoid introducing a new argument which later will become unnecessary.  So, how about this:

- We add a flag in ScmRegexp whether it will need grapheme marking.
- Scm_RegExec calls grapheme marker if necessary.  Pack the result in a new struct (array of indexes, start, and end offset) so that we can make it lazy later.  rex() receives an extra argument that is a precomputed grapheme marks, and put it in match_ctx.

**Comment by shirok** [comment]
Added doc to call Scheme from C

https://github.com/shirok/Gauche/blob/master/doc/HOWTO-callback-scheme.adoc

**Comment by pclouds** [comment]
Woohoo! SRFI 115 is done!
